# Generated by Django 2.2 on 2019-04-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190429_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='articles/'),
        ),
    ]
