# Generated by Django 2.2 on 2019-06-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190429_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='NULL', null=True, upload_to='articles/'),
        ),
    ]
